# Generated by Django 2.0 on 2017-12-19 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ca',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Obecne umiejętności'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pa',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Potencjalne umiejętnośći'),
        ),
    ]
