# Generated by Django 2.0 on 2017-12-19 21:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0002_auto_20171219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ca',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], verbose_name='Obecne umiejętności'),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(verbose_name='Dodatkowy opis'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hajto',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'gra z wątroby'), (2, 'nie gubi chleba'), (3, 'truskawka na torcie'), (4, 'ma automatyzmy'), (5, 'jest turbo'), (6, 'gra z kija'), (7, 'ma detale'), (8, 'gra piłkę życzliwą'), (9, 'widać, że mu się chce')], max_length=17, verbose_name='cechy by Hajto'),
        ),
        migrations.AlterField(
            model_name='player',
            name='leg',
            field=models.IntegerField(choices=[(1, 'lewa'), (2, 'prawa'), (3, 'obie'), (4, 'obie ch***we')], verbose_name='Preferowana noga'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pa',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], verbose_name='Potencjalne umiejętnośći'),
        ),
    ]
