# Generated by Django 2.0 on 2017-12-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0003_auto_20171219_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clubs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scout.Club', verbose_name='Klub'),
        ),
    ]
