# Generated by Django 2.0 on 2017-12-20 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0004_auto_20171219_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Wzrost'),
            preserve_default=False,
        ),
    ]
