# Generated by Django 2.0 on 2017-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0005_player_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist_name', models.CharField(max_length=64, verbose_name='Nazwa shortlisty')),
                ('players', models.ManyToManyField(default=0, to='Scout.Player', verbose_name='Lista piłkarzy')),
            ],
        ),
    ]
