# Generated by Django 2.0 on 2017-12-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scout', '0006_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='arena_name',
            field=models.CharField(max_length=64, verbose_name='Nazwa stadionu'),
        ),
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.CharField(max_length=64, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
    ]
