# Generated by Django 2.0 on 2017-12-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scout', '0007_auto_20171221_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='loged_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='players',
            field=models.ManyToManyField(default=0, null=True, to='Scout.Player', verbose_name='Lista piłkarzy'),
        ),
    ]
